drop table country if exists;

create table country (
  id          integer NOT NULL PRIMARY KEY,
  countryname varchar(32),
  countrycode VARCHAR(2) DEFAULT 'HH',
  version     INTEGER DEFAULT 1 NOT NULL
);

drop table user_info if exists;

--用户信息表
create table user_info (
  id integer GENERATED BY DEFAULT AS IDENTITY(START WITH 6) NOT NULL PRIMARY KEY,
  username varchar(32) NOT NULL,
  password varchar(32) DEFAULT '12345678',
  usertype varchar(2),
  enabled  integer,
  realname varchar(50),
  qq varchar(12),
  email varchar(100),
  address varchar(200),
  tel varchar(30)
);

insert into user_info (id,username,password,usertype) values (1,'test1','12345678','1');
insert into user_info (id,username,password,usertype) values (2,'test2','aaaa','2');
insert into user_info (id,username,password,usertype) values (3,'test3','bbbb','1');
insert into user_info (id,username,password,usertype) values (4,'test4','cccc','2');
insert into user_info (id,username,password,usertype) values (5,'test5','dddd','1');

INSERT INTO country (id, countryname, countrycode, version) VALUES (1, 'Angola', 'AO', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (2, 'Afghanistan', 'AF', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (3, 'Albania', 'AL', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (4, 'Algeria', 'DZ', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (5, 'Andorra', 'AD', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (6, 'Anguilla', 'AI', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (7, 'Antigua and Barbuda', 'AG', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (8, 'Argentina', 'AR', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (9, 'Armenia', 'AM', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (10, 'Australia', 'AU', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (11, 'Austria', 'AT', 1);
INSERT INTO country (id, countryname, countrycode, version) VALUES (12, 'Azerbaijan', 'AZ', 1);